// automatically generated by the FlatBuffers compiler, do not modify

package Common

const (
	OperationCodeOperationCode_NONE    = 0
	OperationCodeNEED_EXCHANGE_TILE    = 1
	OperationCodeEXCHANGE_TILE_RESULT  = 2
	OperationCodeNEED_LACK_TILE        = 3
	OperationCodeLACK_TILE_RESULT      = 4
	OperationCodeDRAW                  = 5
	OperationCodeDRAW_AFTER_KONG       = 6
	OperationCodePLAY                  = 7
	OperationCodeCHOW                  = 8
	OperationCodePONG                  = 9
	OperationCodeKONG                  = 10
	OperationCodeKONG_DARK             = 11
	OperationCodeKONG_TURN             = 12
	OperationCodeTING                  = 13
	OperationCodeBAO_TING              = 14
	OperationCodeWIN                   = 15
	OperationCodeWIN_AFTER_KONG_TURN   = 16
	OperationCodeWIN_SELF              = 17
	OperationCodePASS                  = 18
	OperationCodePASS_CANCEL           = 19
	OperationCodeSHOW_HAND_TILE        = 20
	OperationCodeCHIKEN_DRAW           = 21
	OperationCodeCHIKEN_ROLLER         = 22
	OperationCodeCHIKEN_RESPONSIBILITY = 23
	OperationCodeCHIKEN_CHARGE_BAM1    = 24
	OperationCodeCHIKEN_CHARGE_DOT8    = 25
	OperationCodeWIN_AFTER_KONG_DRAW   = 26
	OperationCodeWIN_AFTER_KONG_PLAY   = 27
	OperationCodeKONG_TURN_FREE        = 28
	OperationCodeLACK_TILE_OK          = 29
	OperationCodeCHIKEN_TUMBLING       = 30
	OperationCodeExtra1                = 60
	OperationCodeExtra2                = 61
	OperationCodeExtra3                = 62
	OperationCodeExtra4                = 63
	OperationCodeExtra5                = 64
	OperationCodeExtra6                = 65
	OperationCodeExtra7                = 66
	OperationCodeExtra8                = 67
	OperationCodeExtra9                = 68
	OperationCodeExtra10               = 69
)

var EnumNamesOperationCode = map[int]string{
	OperationCodeOperationCode_NONE:    "OperationCode_NONE",
	OperationCodeNEED_EXCHANGE_TILE:    "NEED_EXCHANGE_TILE",
	OperationCodeEXCHANGE_TILE_RESULT:  "EXCHANGE_TILE_RESULT",
	OperationCodeNEED_LACK_TILE:        "NEED_LACK_TILE",
	OperationCodeLACK_TILE_RESULT:      "LACK_TILE_RESULT",
	OperationCodeDRAW:                  "DRAW",
	OperationCodeDRAW_AFTER_KONG:       "DRAW_AFTER_KONG",
	OperationCodePLAY:                  "PLAY",
	OperationCodeCHOW:                  "CHOW",
	OperationCodePONG:                  "PONG",
	OperationCodeKONG:                  "KONG",
	OperationCodeKONG_DARK:             "KONG_DARK",
	OperationCodeKONG_TURN:             "KONG_TURN",
	OperationCodeTING:                  "TING",
	OperationCodeBAO_TING:              "BAO_TING",
	OperationCodeWIN:                   "WIN",
	OperationCodeWIN_AFTER_KONG_TURN:   "WIN_AFTER_KONG_TURN",
	OperationCodeWIN_SELF:              "WIN_SELF",
	OperationCodePASS:                  "PASS",
	OperationCodePASS_CANCEL:           "PASS_CANCEL",
	OperationCodeSHOW_HAND_TILE:        "SHOW_HAND_TILE",
	OperationCodeCHIKEN_DRAW:           "CHIKEN_DRAW",
	OperationCodeCHIKEN_ROLLER:         "CHIKEN_ROLLER",
	OperationCodeCHIKEN_RESPONSIBILITY: "CHIKEN_RESPONSIBILITY",
	OperationCodeCHIKEN_CHARGE_BAM1:    "CHIKEN_CHARGE_BAM1",
	OperationCodeCHIKEN_CHARGE_DOT8:    "CHIKEN_CHARGE_DOT8",
	OperationCodeWIN_AFTER_KONG_DRAW:   "WIN_AFTER_KONG_DRAW",
	OperationCodeWIN_AFTER_KONG_PLAY:   "WIN_AFTER_KONG_PLAY",
	OperationCodeKONG_TURN_FREE:        "KONG_TURN_FREE",
	OperationCodeLACK_TILE_OK:          "LACK_TILE_OK",
	OperationCodeCHIKEN_TUMBLING:       "CHIKEN_TUMBLING",
	OperationCodeExtra1:                "Extra1",
	OperationCodeExtra2:                "Extra2",
	OperationCodeExtra3:                "Extra3",
	OperationCodeExtra4:                "Extra4",
	OperationCodeExtra5:                "Extra5",
	OperationCodeExtra6:                "Extra6",
	OperationCodeExtra7:                "Extra7",
	OperationCodeExtra8:                "Extra8",
	OperationCodeExtra9:                "Extra9",
	OperationCodeExtra10:               "Extra10",
}
